# [START gae_python38_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: postgres
  CLOUD_SQL_PASSWORD: nuno
  CLOUD_SQL_DATABASE_NAME: guestbook
  CLOUD_SQL_CONNECTION_NAME: testing-295318:us-central1:teste
# [END gae_python38_cloudsql_config]

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /sass
  static_dir: sass

- url: /(.*\.json)
  static_files: static/\1
  upload: static/(.*\.json)
  
- url: /(.*\.txt)
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.bin)
  static_files: static/\1
  upload: static/(.*\.bin)
  
